inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 4.0
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'config/puma.rb'
    - 'db/schema.rb'
    - 'db/queue_schema.rb'
    - 'db/migrate/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
    - 'lib/tasks/**/*'

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 5
