# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59ad57bd7159db229befacdbaa385611a34fc9f82232196352ce6784d78ea5ef8504de6404712ef6e189e4f327b3ba8a8684c7b974899a074ee618995be2738b

test:
  secret_key_base: 98949616c4e6d4783419ffad7d389fdf349eebbf1f9cd47ffbe64a6c2cd6efdf5c1759b999cfb63274037bfd0d2c927058d1fed995af58ea3ae5e1c27747f3f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
